### ISSUE TITLE
Exclusion patterns wrongly validated

### ISSUE THREAD

**Issue by rmannibucau** [blackducksoftware/hub-common#152]
Hi,

The validation of the exclude patterns is not aligned on the filter implementation.

In particular, https://github.com/blackducksoftware/hub-common/blob/master/src/main/java/com/blackducksoftware/integration/hub/validator/HubScanConfigValidator.java#L179, prevents to exclude files to be scanned, including jar/zip files which can be bothering.

Romain

**Comment by jamesrichard91** [comment]
The validation is to ensure the patterns follow the requirements of the Hub CLI --exclude option. The Hub documentation for "Running a component scan using the command line" should clarify the requirements.

**Comment by rmannibucau** [comment]
@jamesrichard91 hello James, the help you mention says:

>      --exclude <pattern>                Specify a pattern to exclude from
>                                        the scan; patterns must start and
>                                        end with '/' and must not contain
>                                        '**'

Which is the validation which is done but if you check com.blackducksoftware.rxfiles.file.Filter$PatternPathMatcher you realize this validation is abusive and prevents to use file exclusions. This is very impacting for *.jar (javadoc, source artifacts) and any *zip kind of file cause you may not want to exclude target/* (for maven) from being scanned but exclude the javadoc/source/bundle to be scanned which is not possible with these rules which only allow *folders* to be excluded due to the ending /:

    private static PatternPathMatcher create(String rawPattern, Path directory)
    {
      String pattern = rawPattern;
      boolean negate = false;
      boolean directoryOnly = false;
      if (pattern.charAt(0) == '!')
      {
        negate = true;
        pattern = pattern.substring(1);
      }
      if (pattern.startsWith("\\!")) {
        pattern = pattern.substring(1);
      }
      if (pattern.charAt(pattern.length() - 1) == '/')
      {
        directoryOnly = true;
        pattern = pattern.substring(0, pattern.length() - 1);
      }
      boolean pathnameMatch = CharMatcher.is('/').matchesAnyOf(pattern);
      if (pattern.charAt(0) == '/') {
        pattern = pattern.substring(1);
      }
      return new PatternPathMatcher(pattern, directory, negate, directoryOnly, pathnameMatch);
    }

**Comment by jamesrichard91** [comment]
In which project is com.blackducksoftware.rxfiles.file.Filter$PatternPathMatcher? is this code you have written?

**Comment by rmannibucau** [comment]
No, it is bundled with scan.cli.impl-standalone.jar (downloaded by hub-detect) and it comes from the scanframework (v2.3.2) dependency which is where the exclusions are propagated to for the scanning.

**Comment by jamesrichard91** [comment]
Are you decompiling that class file?

**Comment by rmannibucau** [comment]
Yep. The exclusion explanations online were not enough to understand how it works.

**Comment by akamen** [comment]
Hi @rmannibucau posting decompiled source from commercially licensed software may not be a great idea, could you please edit your post to remove that block of code please?

**Comment by jamesrichard91** [comment]
Aside from any license violations, the public documentation for the Hub specifies that the patterns only support excluding directories.  So if you want to exclude individual files that would be a change in the Hub scan CLI and not in this project.

**Comment by rmannibucau** [comment]
@akamen updated
@jamesrichard91 since this project owns the validation it can need to be in both yes

**Comment by jamesrichard91** [comment]
Yes we will have to update once the scan CLI is updated
