### ISSUE TITLE
Running Signature Scanner from Hub Detect on Alpine Linux fails due to Oracle JVM

### ISSUE THREAD

**Issue by joc0611** [blackducksoftware/hub-common#224]
I'm currently trying to run Hub Detect version 4.2.1 inside an ``openjdk:8-jre-alpine`` docker container. My Hub installation, and hence the ``scan.cli.zip``, is version 4.5.0. 

The ``scan.cli.zip`` is packaged with an Oracle JRE, which is not compatible with Alpine Linux (see [Alpine Linux Caveats](https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md#incompatible-binaries). For this reason, the signature scanner is failing with 

```
There was a problem scanning target '/home/jenkins/webapp-backend' : Exception executing the cli scan: Cannot run program "/home/jenkins/workspace/Blackduck/WebApp/tools/Hub_Scan_Installation/scan.cli-4.5.0/jre/bin/java": error=2, No such file or directory
```

Running the signature scanner from it's own ``/home/jenkins/workspace/Blackduck/WebApp/tools/Hub_Scan_Installation/scan.cli-4.5.0/bin/scan.cli.sh`` works fine, if the environment variable ``BDS_JAVA_HOME`` is set to the default OpenJDK JRE of the docker image.

However, Hub Detect 4.2.1 (through hub-common-37.0.0) seems to invoke the signature scanner directly from their Java code, ignoring the ``BDS_JAVA_HOME`` variable. I think the correct place for taking ``BDS_JAVA_HOME`` into consideration would be ``com.synopsys.integration.blackduck.cli.SimpleScanUtility#setupAndExecuteScan(com.synopsys.integration.blackduck.cli.CLILocation)``

Is my observation correct? Are there any known workarounds to invoke signature scanning from Hub Detect using the systems default JRE?

Any help is appreciated. Thanks!

**Comment by ekerwin** [comment]
No workarounds for this right now - we'll try and get a fix in place to use the BDS_JAVA_HOME if it is set asap.

**Comment by jolangbein** [comment]
I can provide a PR, if that helps? I would adapt the method ``setupAndExecuteScan`` as mentioned above.

**Comment by ekerwin** [comment]
Wow - this is really great. This def. helps! I should be able to get this merged this week and release on Thursday.

**Comment by joc0611** [comment]
Cool, thanks! If you want to, let me know how you handled the coverage issue. For potential PRs in the future :-)

**Comment by joc0611** [comment]
Will be fixed in #227

**Comment by joc0611** [comment]
I made a mistake in my first commit: The line https://github.com/blackducksoftware/hub-common/blob/6eb3ddd449e2c24f1461e25850cb5a0996428251/src/main/java/com/synopsys/integration/blackduck/signaturescanner/command/ScanPathsUtility.java#L100 is missing a call to ``findPathToJavaExe``

I will provide another PR tonight

**Comment by akamen** [comment]
Thank you @joc0611 !
