### ISSUE TITLE
Version and project check validation fails

### ISSUE THREAD

**Issue by akamen** [blackducksoftware/hub-common#3]

**Comment by psantos1113** [comment]
Changes were made to address this issue by using a JsonParser object to get an instance of JsonObject.  This is the correct way to parse the Json.  The changes to address this issue were in:
Validation_Improvements: fa6a9d41c19700206d3e465475ad6e26e5d9bd75
master: fa6a9d41c19700206d3e465475ad6e26e5d9bd75
