### ISSUE TITLE
Failed to retrieve cookies

### ISSUE THREAD

**Issue by jrichardBD** [blackducksoftware/hub-common#6]
ERROR: Could not establish connection to 'https://hub-bds.blackducksoftware.com/' . Failed to retrieve cookies
ERROR: com.blackducksoftware.integration.hub.exception.HubIntegrationException: Could not establish connection to 'https://hub-bds.blackducksoftware.com/' . Failed to retrieve cookies
at com.blackducksoftware.integration.hub.HubIntRestService.setCookies(HubIntRestService.java:275)

**Comment by jrichardBD** [comment]
Turns out we have been checking for the Header Set-Cookie as well as Cookie. When we get the Set-Cookie list we check if it is null or empty and if that is true then we throw the exception seen in the description. We should only be checking the Cookie header, I am not sure how this ever worked but it will be fixed

**Comment by nutant-h** [comment]
Just encountered this.

**Comment by jamesrichard91** [comment]
What version of blackduck-common are you using?

**Comment by nutant-h** [comment]
I am using `blackduck==0.0.30` python lib

**Comment by ekerwin** [comment]
This project is a Black Duck library written in java. The integration team in Synopsys that works with this project does not support any python library for Black Duck. If you are having an issue with a python library, you should find that project and let them know there's an issue.
